CREATE TABLE BaiTapKHDL3.HANGHANGKHONG
(
    MAHANG VARCHAR(2) CONSTRAINT PK_HHK PRIMARY KEY,
    TENHANG VARCHAR(40),
    NGTL DATE,
    DUONGBAY NUMBER
)

CREATE TABLE BaiTapKHDL3.CHUYENBAY
(
    MACB VARCHAR(5) CONSTRAINT PK_CB PRIMARY KEY,
    MAHANG VARCHAR(2),
    XUATPHAT VARCHAR(20),
    DIEMDEN VARCHAR(20), 
    BATDAU DATE,
    TGBAY DECIMAL
)

CREATE TABLE BaiTapKHDL3.NHANVIEN
(
    MANV VARCHAR(5) CONSTRAINT PL_NV PRIMARY KEY,
    HOTEN VARCHAR(30),
    GIOITINH VARCHAR(3),
    NGAYSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR(20)
)

CREATE TABLE BaiTapKHDL3.PHANCONG
(
    MACB VARCHAR(5),
    MANV VARCHAR(4),
    NHIEMVU VARCHAR(25)
)
ALTER USER BaiTapKHDL3 QUOTA UNLIMITED ON USERS;
ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

INSERT INTO BaiTapKHDL3.HANGHANGKHONG
VALUES ('VN', 'Vietnam Airline', '15/01/1956', 52);
INSERT INTO BaiTapKHDL3.HANGHANGKHONG
VALUES ('VJ', 'Vietjet Air', '25/12/2011', 33);
INSERT INTO BaiTapKHDL3.HANGHANGKHONG
VALUES ('BL', 'Jetstar Pacific Airline', '01/12/1990', 33);

INSERT INTO BaiTapKHDL3.CHUYENBAY
VALUES ('VN550', 'VN', 'TP.HCM', 'Singapore', '20/12/2015 13:15', 2);
INSERT INTO BaiTapKHDL3.CHUYENBAY
VALUES ('VJ331', 'VJ', 'Da Nang', 'Vinh', '28/12/2015 22:30', 1);
INSERT INTO BaiTapKHDL3.CHUYENBAY
VALUES ('BL696','BL', 'TP.HCM', 'Da Lat', '24/12/2015 06:00', 0.5);

INSERT INTO BaiTapKHDL3.NHANVIEN
VALUES ('NV01','Lam Van Ben', 'Nam','10/09/1978', '05/06/2000', 'Phi cong');
INSERT INTO BaiTapKHDL3.NHANVIEN
VALUES ('NV02','Duong Thi Luc', 'Nu','22/03/1989', '12/11/2013', 'Tiep vien');
INSERT INTO BaiTapKHDL3.NHANVIEN
VALUES ('NV03','Hoang Thanh Tung', 'Nam', '29/07/1982', '11/04/2007','Tiep vien');

INSERT INTO BaiTapKHDL3.PHANCONG
VALUES ('VN550', 'NV01', 'Co truong');
INSERT INTO BaiTapKHDL3.PHANCONG
VALUES ('VN550', 'NV02', 'Tiep vien');
INSERT INTO BaiTapKHDL3.PHANCONG
VALUES ('BL696', 'NV03', 'Tiep vien truong');


-- Cau5
SELECT * FROM BaiTapKHDL3.NHANVIEN NV
WHERE EXTRACT(MONTH FROM(NV.NGAYSINH))=7;

--Cau6
SELECT PC.MACB FROM BaiTapKHDL3.PHANCONG PC 
GROUP BY PC.MACB
HAVING COUNT(PC.MACB) >= ALL(
    SELECT COUNT(MACB) FROM BaiTapKHDL3.PHANCONG
    GROUP BY MACB ) ;

-- Cau7
SELECT CB.MAHANG 
    FROM BaiTapKHDL3.CHUYENBAY CB JOIN BaiTapKHDL3.PHANCONG PC 
            ON CB.MACB = PC.MACB
    WHERE CB.XUATPHAT = 'Da Nang'
    GROUP BY CB.MAHANG 
    HAVING COUNT(PC.MACB) < 2;

--Cau8
SELECT * 
FROM BaiTapKHDL3.NHANVIEN NV
WHERE NOT EXISTS (
    SELECT * FROM BaiTapKHDL3.CHUYENBAY CB
        WHERE NOT EXISTS (
            SELECT * FROM BaiTapKHDL3.PHANCONG PC
            WHERE NV.MANV = PC.MANV AND CB.MACB = PC.MACB ) );
                
                
                