/*1. TAO BANG XE*/
CREATE TABLE BaiTapCNTT1.XE
(
    MAXE VARCHAR2(3) CONSTRAINT PK_XE PRIMARY KEY,
    BIENKS VARCHAR2(10) ,
    MATUYEN VARCHAR(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER
)
/*2. BANG TUYEN */
CREATE TABLE BaiTapCNTT1.TUYEN
(
    MATUYEN VARCHAR(4) CONSTRAINT PK_TUYEN PRIMARY KEY,
    BENDAU VARCHAR(3) NOT NULL,
    BENCUOI VARCHAR(3) NOT NULL,
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK NUMBER
)
/* 3.BANG KHACH*/
CREATE TABLE BaiTapCNTT1.KHACH
(
   MAKH VARCHAR(4) CONSTRAINT PK_KHACH PRIMARY KEY,
   HOTREN VARCHAR(50),
   GIOITINH VARCHAR(3),
   CMND NUMBER(11)
)
/* 4.BANG VE XE*/
CREATE TABLE BaiTapCNTT1.VEXE
(
    MATUYEN VARCHAR(4),
    MAKH VARCHAR(4) NOT NULL,
    NGMUA DATE,
    GIAVE DECIMAL
)

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';
--INSERT DATA 
--INSERT TABLE XE
INSERT INTO BaiTapCNTT1.XE VALUES('X01', '52LD-4393', 'T11A', 20, 20);
INSERT INTO BaiTapCNTT1.XE VALUES('X02', '59LD-7247', 'T32D', 36, 36);
INSERT INTO BaiTapCNTT1.XE VALUES('X03', '55LD-6850','T06F', 15, 15);
--INSERT TABLE TUYEN
INSERT INTO BaiTapCNTT1.TUYEN VALUES('T11A', 'SG', 'DL', 210000, '30/12/2016', 6);
INSERT INTO BaiTapCNTT1.TUYEN VALUES('T32D', 'PT', 'SG', 120000, '26/12/2016', 4);
INSERT INTO BaiTapCNTT1.TUYEN VALUES('T06F', 'NT', 'DVG', 225000, '02/01/2017', 7);


--INSERT TABLE KHACH
INSERT INTO BaiTapCNTT1.KHACH VALUES ('KH01', 'Lam Van Ben', 'Nam', 655615896);
INSERT INTO BaiTapCNTT1.KHACH VALUES ('KH02','Duong Thi Luc', 'Nu', 275648642);
INSERT INTO BaiTapCNTT1.KHACH VALUES ('Kh03','Hoang Thanh Tung', 'Nam', 456889143);

--INSERT TABLE VEXE 

INSERT INTO BaiTapCNTT1.VEXE VALUES
('T11A','KH01','20/12/2016',210000);
INSERT INTO BaiTapCNTT1.VEXE VALUES
('T32D','KH02','25/12/2016',144000);
INSERT INTO BaiTapCNTT1.VEXE VALUES
('T06F','KH03','30/12/2016',270000);

--3.cac tuyen xe co thoi gian du kien lon hon 5 tieng luon co gia tuyen lon hon 200.000

CREATE TRIGGER TRG_GIA_TUYEN ON BaiTapCNTT1.TUYEN
FOR INSERT, UPDATE
AS
BEGIN
    DECLARE @GIA DECIMAL, @TGDK DATE, @MATUYEN  VARCHAR(4)
    SELECT @GIA = GIATUYEN, @TGDK = TGDK FORM INSERTED
    IF(@GIA >= 200 AND @TGDK >5)
        BEGIN 
            PRINT 'SUCCESS'
        END
    ELSE
        BEGIN
            PRINT 'FAILED'
            ROLLBACK TRANSACTION
        END
END
--4. TUYEN XE CÓ NGAY XUAT BEN TU NGAY 29/12/2016 DEN NGAY 05/01/2017 SE CÓ GIA VE TANG 20%
UPDATE BaiTapCNTT1.TUYEN
SET GIATUYEN = GIATUYEN*1.2
WHERE TRUNC(TGDK) >= TO_DATE('05/01/2017', 'DD/MM/YYYY') 
    AND  TRUNC(TGDK) >= TO_DATE('29/12/2016', 'DD/MM/YYYY')


SELECT * FROM BaiTapCNTT1.TUYEN
--5. TIM TAT CAC CAC VE XE MUA TRONG THANG 12 SAP XEP KET QUA GIAM GIAM THEO GIA VE
SELECT * FROM BaiTapCNTT1.VEXE
WHERE EXTRACT(MONTH FROM(NGMUA))=12
ORDER BY GIAVE DESC


--6. TIM TUYEN XE CO SO VE XE IT NHAT TRONG NAM 2016
SELECT MATUYEN FROM BaiTapCNTT1.VEXE 
WHERE EXTRACT(YEAR FROM(NGMUA))=2016
GROUP BY MATUYEN
HAVING COUNT(MATUYEN) <= ALL
                        (
                        SELECT COUNT(MATUYEN) FROM BaiTapCNTT1.VEXE 
                            WHERE EXTRACT(YEAR FROM(NGMUA))=2016
                            GROUP BY MATUYEN 
                        );

--7.TIM TUYEN XE CO CA HANH KHACH NAM VA HANH KHACH NU MUA VE
SELECT * 
    FROM BaiTapCNTT1.TUYEN  C
JOIN(
SELECT A.MATUYEN 
    FROM BaiTapCNTT1.VEXE A JOIN BaiTapCNTT1.KHACH B ON A.MAKH = B.MAKH
        WHERE GIOITINH = 'Nam' and GIOITINH ='Nu') D
ON C.MATUYEN = D.MATUYEN;

--8.TIM HANH KHACH NU DA TUNG MUA VE TAT CAC CAC TUYEN XE
SELECT * FROM BaiTapCNTT1.KHACH KH
    WHERE GIOITINH = 'Nu' and  NOT EXISTS (
                    SELECT * FROM BaiTapCNTT1.TUYEN TU
                        WHERE NOT EXISTS (
                            SELECT * FROM BaiTapCNTT1.VEXE VX 
                                WHERE TU.MATUYEN = VX.MATUYEN AND KH.MAKH = VX.MAKH)
                )





