
CREATE TABLE BaiTapCNTT2.USER_NEW
(
    U_ID VARCHAR(3) CONSTRAINT PK_USER PRIMARY KEY,
    USERNAME VARCHAR(15),
    PASS VARCHAR(15),
    REGDAY DATE,
    NATIONALITY VARCHAR(15)
)

CREATE TABLE BaiTapCNTT2.CHANNEL
(
    CHANNELID VARCHAR(4) CONSTRAINT PK_CHANNEL PRIMARY KEY,
    CNAME VARCHAR(30),
    SUBSCRIBES NUMBER,
    OWNNER VARCHAR(3),
    CREATED DATE
)

CREATE TABLE BaiTapCNTT2.VIDEO
(
    VIDEOID VARCHAR(7) CONSTRAINT PK_VIDEO PRIMARY KEY,
    TITLE VARCHAR(100),
    DERATION NUMBER,
    AGE NUMBER
)

CREATE TABLE BaiTapCNTT2.SHARE_NEW
(
    VIDEOID VARCHAR(7),
    CHANNELID VARCHAR(4)
)

--INSERT TABLE USERNEW
INSERT INTO  BaiTapCNTT2.USER_NEW
VALUES('001', 'faptv', '123456abc','01/01/2014', 'viet nam');

INSERT INTO  BaiTapCNTT2.USER_NEW 
VALUES('002', 'kemxoitv', '@147869','05/06/2015', 'campuchia');

INSERT INTO  BaiTapCNTT2.USER_NEW 
VALUES('003', 'openshare', 'qwertyuiop','12/05/2009', 'viet nam');

--INSERT TABLE CHANNEL

INSERT INTO  BaiTapCNTT2.CHANNEL
VALUES ('C120', 'FAP TV', 2343, 001, '02/01/2014');

INSERT INTO  BaiTapCNTT2.CHANNEL
VALUES ('C905', 'KEM XOI TV', 1032, 002, '10/07/2015');

INSERT INTO  BaiTapCNTT2.CHANNEL
VALUES ('C357', 'OpenShare Cafe', 5064, 003, '10/12/2010');

--INSERT INTO VIDEO 
INSERT INTO  BaiTapCNTT2.VIDEO
VALUES ('V100229', 'FAPtv Com Nguoi Tap 41-Dot Nhap', 469, 18);
INSERT INTO  BaiTapCNTT2.VIDEO
VALUES ('V211002', 'Kem xoi: Tap 31-may Kool tinh yeu cua anh', 312, 16);
INSERT INTO  BaiTapCNTT2.VIDEO
VALUES ('V400002', 'Noi tinh yeu ket thuc-Hoang Tuan', 378, 0);

--INSERT TABLE SHARE

INSERT INTO  BaiTapCNTT2.SHARE_NEW
VALUES('V100229','C905' );

INSERT INTO  BaiTapCNTT2.SHARE_NEW
VALUES('V211002','C120' );


INSERT INTO  BaiTapCNTT2.SHARE_NEW
VALUES('V400002','C357' );

--5. TIM CAC VIDEO CO GIOI HAN DO TUOI TU 16 TRO LEN 

SELECT *FROM BaiTapCNTT2.VIDEO WHERE AGE >= 16;


--6.KENH CO SO NGUOI THEO DOI NHIEU NHAT 
SELECT * 
FROM (SELECT * FROM BaiTapCNTT2.CHANNEL 
            ORDER BY SUBSCRIBES DESC )
WHERE ROWNUM = 1;


--7. VOI MOI VIDEO CO GIOI HAN DO TUOI LA 18, THONG KE SO KENH DA CHIA SE 

SELECT A.VIDEOID, COUNT(B.CHANNELID) FROM BaiTapCNTT2.VIDEO A JOIN BaiTapCNTT2.SHARE_NEW B
        ON A.VIDEOID = B.VIDEOID
WHERE AGE = 18
GROUP BY A.VIDEOID;


--8. TIM VIDEO DUOC TAT CA CAC KENH CHIA SE 
SELECT * FROM BaiTapCNTT2.VIDEO A
WHERE NOT EXISTS
                (
                SELECT * FROM BaiTapCNTT2.CHANNEL B
                        WHERE NOT EXISTS
                                        (
                                        SELECT * FROM BaiTapCNTT2.SHARE_NEW  C
                                        WHERE A.VIDEOID = C.VIDEOID 
                                            AND B.CHANNELID = C.CHANNELID
                                        )
                );

