ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';
--Cau 1: tao 4 table HANGHANGKHONG, CHUYENBAY, NHANVIEN,PHANCONG
CREATE TABLE BAITHI3.HANGHANGKHONG
(
    MAHANG VARCHAR2(2) PRIMARY KEY,
    TENHANG VARCHAR2(50),
    NGTL DATE,
    DUONGBAY NUMBER
);

CREATE TABLE BAITHI3.CHUYENBAY
(
    MACB VARCHAR2(5) PRIMARY KEY,
    MAHANG VARCHAR2(2),
    XUATPHAT VARCHAR2(20),
    DIEMDEN VARCHAR2(20),
    BATDAU DATE,
    TGBAY FLOAT
);

CREATE TABLE BAITHI3.NHANVIEN 
(
    MANV VARCHAR2(4) PRIMARY KEY,
    HOTEN VARCHAR2(30),
    GIOITINH VARCHAR2(5),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR2(15)
);

CREATE TABLE BAITHI3.PHANCONG
(
    MACB VARCHAR2(5),
    MANV VARCHAR2(4),
    NHIEMVU VARCHAR2(20),
    CONSTRAINT pk_pc PRIMARY KEY (MACB,MANV)
);

--Cau 2:Nhap du lieu cho 4 table nhu de bai
INSERT INTO BAITHI3.HANGHANGKHONG VALUES ('VN','Vietnam Airlines','15/01/1956'
,52);
INSERT INTO BAITHI3.HANGHANGKHONG VALUES ('VJ','Vietjet Air','25/12/2011',33);
INSERT INTO BAITHI3.HANGHANGKHONG VALUES ('BL','Jetstar Pacific Airlines',
'01/12/1990',13);

INSERT INTO BAITHI3.CHUYENBAY VALUES ('VN550','VN','TP.HCM','Singapore',
'20/12/2015 13:15:00',2);
INSERT INTO BAITHI3.CHUYENBAY VALUES ('VJ331','VJ','Da Nang','Vinh',
'28/12/2015 22:30:00', 1);
INSERT INTO BAITHI3.CHUYENBAY VALUES ('BL696','BL','TP. HCM','Da Lat',
'24/12/2015 06:00:00', 0.5);

INSERT INTO BAITHI3.NHANVIEN VALUES('NV01', 'lam Van Ben' ,'Nam' ,'10/09/1978',
'05/06/2000' ,'Phi cong');
INSERT INTO BAITHI3.NHANVIEN VALUES('NV02','Duong Thi Luc', 'Nu','22/03/1989',
'12/11/2013', 'Tiep vien');
INSERT INTO BAITHI3.NHANVIEN VALUES('NV03','Hoang Thanh Tung','Nam',
'29/07/1983','11/04/2007','Tiep vien');

INSERT INTO BAITHI3.PHANCONG VALUES ('VN550','NV01','Co truong');
INSERT INTO BAITHI3.PHANCONG VALUES ('VN550','NV02','Tiep vien');
INSERT INTO BAITHI3.PHANCONG VALUES ('BL696','NV03','Tiep vien truong');
--Cau 3: Chuyen mon cua nhan vien chi duoc la 'Phi cong' hoac 'Tiep vien'
ALTER TABLE BAITHI3.NHANVIEN ADD CONSTRAINT check_chuyenmon 
CHECK (CHUYENMON='Phi cong' OR CHUYENMON='Tiep vien');
--Cau 4: Ngay bat dau moi chuyen bay luon lon hon ngay thanh lap hang hang khong
--quan ly chuyen bay do

--Cau 5: Tat ca cac nhan vien co sinh nhat trong thang 7
SELECT * FROM BAITHI3.NHANVIEN WHERE EXTRACT(MONTH FROM NGSINH)=7;
--Cau 6: Chuyen bay co so nhan vien nhieu nhat
SELECT MACB,COUNT(*) as SoNV FROM BAITHI3.PHANCONG 
GROUP BY MACB
HAVING COUNT(*) >= ALL(SELECT COUNT(MANV) FROM BAITHI3.PHANCONG
                       GROUP BY MACB);
--Cau 7:Voi moi hang hang khong, thong ke so chuyen bay co diem xuat phat la 
-- Da Nang va co so nhan vien duoc phan cong it hon 2
SELECT a.MAHANG,COUNT(MACB) AS SOCB 
FROM BAITHI3.HANGHANGKHONG a,BAITHI3.CHUYENBAY b
WHERE a.MAHANG=b.MAHANG 
      AND XUATPHAT='Da Nang'
      AND MACB IN (SELECT a.MACB FROM BAITHI3.CHUYENBAY a
                   LEFT OUTER JOIN BAITHI3.PHANCONG b
                   ON a.MACB=b.MACB
                   GROUP BY a.MACB
                   HAVING COUNT(MANV)<2)
GROUP BY a.MAHANG;
--Cau 8: Tim nhan vien tham gia tat ca cac chuyen bay
SELECT * FROM BAITHI3.NHANVIEN a
WHERE NOT EXISTS (SELECT * FROM BAITHI3.CHUYENBAY b
                  WHERE NOT EXISTS (SELECT * FROM BAITHI3.PHANCONG c
                                    WHERE a.MANV=c.MANV AND c.MACB=b.MACB)); 

