ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';
--Cau 1:tao 4 table USER, CHANNEL, VIDEO, SARE
create table BAITHI2.USER_NEW
(
    U_ID VARCHAR2(3),
    USERNAME VARCHAR2(30),
    PASS VARCHAR2(30),
    REGDAY DATE,
    NATIONALITY VARCHAR2(30),
    CONSTRAINT pk_USER_NEW PRIMARY KEY (U_ID)
);

create table BAITHI2.CHANNEL
(
    CHANNELID VARCHAR2(4) PRIMARY KEY,
    CNAME VARCHAR2(30),
    SUBSCRIBES NUMBER,
    OWNNER VARCHAR2(3),
    CREATED DATE
);

create table BAITHI2.VIDEO
(
    VIDEOID VARCHAR2(7) PRIMARY KEY,
    TITLE VARCHAR2(200),
    DURATIONS NUMBER,
    AGE NUMBER
);

create table BAITHI2.SARE 
(
    VIDEOID varchar2(7),
    CHANNELID VARCHAR2(4),
    CONSTRAINT pk_SARE primary key (VIDEOID,CHANNELID)
);

--Cau 2: Nhap du lieu cho 4 table nhu de bai
INSERT INTO BAITHI2.USER_NEW VALUES ('001','faptv','123456abc','01/01/2014',
'Viet Nam');
INSERT INTO BAITHI2.USER_NEW VALUES ('002','kemxoitv','@147869iii','05/06/2015',
'Campuchia');
INSERT INTO BAITHI2.USER_NEW VALUES ('003','openshare','qwertyuiop','12/05/2009'
,'Viet Nam');

INSERT INTO BAITHI2.CHANNEL VALUES ('C120','FAPTV',2343,'001','02/01/2014');
INSERT INTO BAITHI2.CHANNEL VALUES ('C905','Kem xoi TV',1032,'002','09/07/2015');
INSERT INTO BAITHI2.CHANNEL VALUES ('C357','OpenShare Cafe',5064,'003',
'10/12/2010');

INSERT INTO BAITHI2.VIDEO VALUES ('V100229','FAPtv Com Nguoi Tap 41 - Dot Nhap',
469,18);
INSERT INTO BAITHI2.VIDEO VALUES ('V211002','Kem xoi: Tap 31 - May Kool tinh yeu
cua anh', 312 ,16);
INSERT INTO BAITHI2.VIDEO VALUES ('V400002','Noi tinh yeu ket thuc - Hoang Tuan',
378, 0);

INSERT INTO BAITHI2.SARE VALUES ('V100229','C905');
INSERT INTO BAITHI2.SARE VALUES ('V211002','C120');
INSERT INTO BAITHI2.SARE VALUES ('V400002','C357');

--Cau 5: Tim tat ca cac video co gioi han do tuoi tu 16 tro len
SELECT * FROM BAITHI2.VIDEO
WHERE AGE>=16;
--Cau 6: Tim kenh co so nguoi theo doi nhieu nhat
SELECT * FROM BAITHI2.CHANNEL
WHERE SUBSCRIBES IN (SELECT SUBSCRIBES FROM BAITHI2.CHANNEL
                     ORDER BY SUBSCRIBES DESC
                     FETCH FIRST 1 ROWS ONLY);
--Cau 7: Voi moi video gioi han do tuoi la 18, thong ke so kenh da chia se
SELECT a.VIDEOID,COUNT(DISTINCT CHANNELID) AS SL 
FROM BAITHI2.SARE a, BAITHI2.VIDEO b
WHERE a.VIDEOID=b.VIDEOID AND AGE=18
GROUP BY a.VIDEOID;
--Cau 8: Tim video duoc tat ca cac kenh chia se
SELECT * FROM BAITHI2.VIDEO a 
WHERE NOT EXISTS (SELECT * FROM BAITHI2.CHANNEL b 
                  WHERE NOT EXISTS (SELECT * FROM BAITHI2.SARE c
                  WHERE a.VIDEOID=c.VIDEOID
                  AND c.CHANNELID=b.CHANNELID));