-- CAU 1
CREATE TABLE BaiTapCNTT1.XE
(
    MAXE VARCHAR2(3) CONSTRAINT PX_XE PRIMARY KEY,
    BIENKS VARCHAR2(10),
    MATUYEN VARCHAR2(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER
)

CREATE TABLE BaiTapCNTT1.TUYEN
(
    MATUYEN VARCHAR2(4) CONSTRAINT PX_TUYEN PRIMARY KEY,
    BENDAU VARCHAR2(3) NOT NULL,
    BENCUOI VARCHAR2(3) NOT NULL,
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK NUMBER
)

CREATE TABLE BaiTapCNTT1.KHACH
(
    MAKH VARCHAR2(4) CONSTRAINT PX_KHACH PRIMARY KEY,
    HOTEN VARCHAR2(50),
    GIOITINH VARCHAR2(3),
    CMND NUMBER(11)
)

CREATE TABLE BaiTapCNTT1.VEXE
(
    MATUYEN VARCHAR2(4),
    MAKH VARCHAR2(4),
    NGMUA DATE, 
    GIAVE DECIMAL, 
    CONSTRAINT PK_VEXE PRIMARY KEY(MATUYEN,MAKH,NGMUA)
)

ALTER TABLE BaiTapCNTT1.XE 
ADD CONSTRAINT FK_TUYEN FOREIGN KEY (MATUYEN) REFERENCES BaiTapCNTT1.TUYEN(MATUYEN)

ALTER TABLE BaiTapCNTT1.VEXE 
ADD CONSTRAINT FK_VEXE1 FOREIGN KEY (MATUYEN) REFERENCES BaiTapCNTT1.TUYEN(MATUYEN)

ALTER TABLE BaiTapCNTT1.VEXE 
ADD CONSTRAINT FK_VEXE2 FOREIGN KEY (MAKH) REFERENCES BaiTapCNTT1.KHACH(MAKH)

-- CAU 2
ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

INSERT INTO BaiTapCNTT1.XE VALUES ('X01','52LD-4393','T11A',20,20);
INSERT INTO BaiTapCNTT1.XE VALUES ('X02','59LD-7247','T32D',36,36);
INSERT INTO BaiTapCNTT1.XE VALUES ('X03','55LD-6850','T06F',15,15);

INSERT INTO BaiTapCNTT1.TUYEN VALUES ('T11A','SG','DL',210000,'26/12/2016',6);
INSERT INTO BaiTapCNTT1.TUYEN VALUES ('T32D','PT','SG',120000,'30/12/2016',4);
INSERT INTO BaiTapCNTT1.TUYEN VALUES ('T06F','NT','DNG',225000,'02/01/2017',7);

INSERT INTO BaiTapCNTT1.KHACH VALUES ('KH01','Lam Van Ben','Nam',655615896);
INSERT INTO BaiTapCNTT1.KHACH VALUES ('KH02','Duong Thi Luc','Nu',275648642);
INSERT INTO BaiTapCNTT1.KHACH VALUES ('KH03','Hoang Thanh Tung','Nam',456889143);

INSERT INTO BaiTapCNTT1.VEXE VALUES ('T11A','KH01','20/12/2016',210000);
INSERT INTO BaiTapCNTT1.VEXE VALUES ('T32D','KH02','25/12/2016',144000);
INSERT INTO BaiTapCNTT1.VEXE VALUES ('T06F','KH03','30/12/2016',270000);

-- CAU 3
ALTER TABLE BaiTapCNTT1.TUYEN
ADD CONSTRAINT C3 CHECK ((TGDK>5 AND GIATUYEN>200000) OR (TGDK<=5));

-- CAU 4


-- CAU 5
SELECT BaiTapCNTT1.VEXE.MATUYEN
FROM BaiTapCNTT1.VEXE
WHERE EXTRACT(MONTH FROM(NGMUA))=12
ORDER BY GIAVE DESC

-- CAU 6
SELECT MATUYEN
FROM BaiTapCNTT1.VEXE
WHERE EXTRACT(YEAR FROM(NGMUA))=2016
GROUP BY MATUYEN
HAVING COUNT(MAKH)<=(
    SELECT MIN(COUNT(MAKH)) 
    FROM BaiTapCNTT1.VEXE
    WHERE EXTRACT(YEAR FROM(NGMUA))=2016
    GROUP BY MATUYEN)
    
-- CAU 7
SELECT MATUYEN
FROM BaiTapCNTT1.VEXE, BaiTapCNTT1.KHACH
WHERE VEXE.MAKH=KHACH.MAKH AND GIOITINH='Nam'
INTERSECT
SELECT MATUYEN
FROM BaiTapCNTT1.VEXE, BaiTapCNTT1.KHACH
WHERE VEXE.MAKH=KHACH.MAKH AND GIOITINH='Nu'

-- CAU 8
SELECT *
FROM BaiTapCNTT1.KHACH K
WHERE GIOITINH='Nu' AND NOT EXISTS(
    SELECT * 
    FROM BaiTapCNTT1.TUYEN T
    WHERE NOT EXISTS(
        SELECT * 
        FROM BaiTapCNTT1.VEXE V
        WHERE V.MATUYEN=T.MATUYEN AND V.MAKH=K.MAKH))
        

