

CREATE TABLE BaiTapKHDL2.USER_NEW
(
 U_ID VARCHAR(3) CONSTRAINT PK_USER_NEW PRIMARY KEY,
 USERNAME VARCHAR(9),
 PASS VARCHAR(11),
 REGDAY DATE,
 NATIONALITY VARCHAR(10)

)


CREATE TABLE BaiTapKHDL2.CHANNEL

(
   CHANNELID VARCHAR(4) CONSTRAINT PK_CHANNEDL PRIMARY KEY,
   CNAME VARCHAR(20),
   SUBSCRIBES VARCHAR(4),
   OWNNER VARCHAR (3),
   CREATED DATE
)


CREATE TABLE BaiTapKHDL2.VIDEO

(
    VIDEOID VARCHAR(7) CONSTRAINT PK_VIDEO PRIMARY KEY,
    TITLE VARCHAR(60),
    DURATION VARCHAR(3),
    AGE VARCHAR(2)
)

CREATE TABLE BaiTapKHDL2.SHARE_NEW

(
    VIDEOID VARCHAR(7),
    CHANNELID VARCHAR(4),
    CONSTRAINT PK_SHARE_NEW PRIMARY KEY(VIDEOID,CHANNELID)
)


ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

ALTER USER BaiTapKHDL2 QUOTA UNLIMITED ON USERS;

INSERT INTO BaiTapKHDL2.USER_NEW VALUES ('001', 'faptv', '123456abc', '01/01/2014', 'Vi?t Nam');
INSERT INTO BaiTapKHDL2.USER_NEW VALUES ('002', 'kemxoitv', '@147869iii', '05/06/2015', 'Campuchia');
INSERT INTO BaiTapKHDL2.USER_NEW VALUES ('003', 'openshare', 'q?ertiuiop', '12/05/2009', 'Vi?t Nam');
SELECT * FROM BaiTapKHDL2.USER_NEW;


INSERT INTO BaiTapKHDL2.CHANNEL VALUES ('C120', 'FAP TV', '2343', '001', '02/01/2014');
INSERT INTO BaiTapKHDL2.CHANNEL VALUES ('C905', 'Kem xôi TV', '1032', '002', '09/07/2015');
INSERT INTO BaiTapKHDL2.CHANNEL VALUES ('C357', 'OpenShare', '5064', '003', '10/12/2010');

INSERT INTO BaiTapKHDL2.VIDEO VALUES ('V100229', 'FAPtv C?m Ngu?i T?p 41 - ??t Nh?p', '469', '18');
INSERT INTO BaiTapKHDL2.VIDEO VALUES ('V211002', 'Kem xôi: T?p 31 - M?y Kool tình yêu c?a anh', '312', '16');
INSERT INTO BaiTapKHDL2.VIDEO VALUES ('V400002', 'N?i tình yêu k?t thúc - Hoàng Tu?n', '378', '0');


INSERT INTO BaiTapKHDL2.SHARE_NEw VALUES ('V100229', 'C905');
INSERT INTO BaiTapKHDL2.SHARE_NEw VALUES ('V211002', 'C120');
INSERT INTO BaiTapKHDL2.SHARE_NEw VALUES ('V$00002', 'C357');



-- Cau5
SELECT *FROM BaiTapKHDL2.VIDEO WHERE AGE >= 16;

-- Cau6
SELECT * 
FROM (SELECT * FROM BaiTapKHDL2.CHANNEL 
            ORDER BY SUBSCRIBES DESC )
WHERE ROWNUM = 1;

-- Cau7
SELECT A.VIDEOID, COUNT(B.CHANNELID)
FROM BaiTapKHDL2.VIDEO A JOIN BaiTapKHDL2.SHARE_NEW B
ON A.VIDEOID = B.VIDEOID
WHERE AGE = 18
GROUP BY A.VIDEOID;


-- Cau8
SELECT * 
FROM BaiTapKHDL2.VIDEO A
WHERE NOT EXISTS(
    SELECT * FROM BaiTapKHDL2.CHANNEL B
        WHERE NOT EXISTS(
            SELECT * FROM BaiTapKHDL2.SHARE_NEW  C
                WHERE A.VIDEOID = C.VIDEOID 
                     AND B.CHANNELID = C.CHANNELID
                        )
                );


