-- CAU 1
CREATE TABLE BaiTapCNTT2.USER_NEW
(
    U_ID VARCHAR2(3) CONSTRAINT PX_USER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASS VARCHAR2(30) NOT NULL,
    REGDAY DATE,
    NATIONALITY VARCHAR2(30)
)

CREATE TABLE BaiTapCNTT2.CHANNEL
(
    CHANNELID VARCHAR2(4) CONSTRAINT PX_CHANNEL PRIMARY KEY,
    CNAME VARCHAR2(30), 
    SUBCRIBES NUMBER,
    OWNNER VARCHAR2(3),
    CREATED DATE
)

CREATE TABLE BaiTapCNTT2.VIDEO 
(
    VIDEOID VARCHAR2(7) CONSTRAINT PX_VIDEO PRIMARY KEY,
    TITLE VARCHAR2(50),
    DURATION NUMBER,
    AGE NUMBER
)

CREATE TABLE BaiTapCNTT2.SHARE_NEW
(
    VIDEOID VARCHAR2(7),
    CHANNELID VARCHAR2(4),
    CONSTRAINT PK_SHARE PRIMARY KEY(VIDEOID,CHANNELID)
)

ALTER TABLE BaiTapCNTT2.SHARE_NEW 
ADD CONSTRAINT FK_SHARE FOREIGN KEY (VIDEOID) REFERENCES BaiTapCNTT2.VIDEO(VIDEOID)

ALTER TABLE BaiTapCNTT2.SHARE_NEW 
ADD CONSTRAINT FK_SHARE1 FOREIGN KEY (CHANNELID) REFERENCES BaiTapCNTT2.CHANNEL(CHANNELID)

-- CAU 2
ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

INSERT INTO BaiTapCNTT2.USER_NEW VALUES ('001','faptv','123456abc','01/01/2014','Viet Nam');
INSERT INTO BaiTapCNTT2.USER_NEW VALUES ('002','kemxoitv','@147869iii','05/06/2015','Campuchia');
INSERT INTO BaiTapCNTT2.USER_NEW VALUES ('003','openshare','qwertyuiop','12/05/2009','Viet Nam');

INSERT INTO BaiTapCNTT2.CHANNEL VALUES ('C120','FAP TV','2343','001','02/01/2014');
INSERT INTO BaiTapCNTT2.CHANNEL VALUES ('C905','Kem Xoi TV','1032','002','09/07/2015');
INSERT INTO BaiTapCNTT2.CHANNEL VALUES ('C357','OpenShare Cafe','5064','003','10/12/2010');

INSERT INTO BaiTapCNTT2.VIDEO VALUES ('V100229','FAPtv Com Nguoi Tap 41 - Dot Nhap','469','18');
INSERT INTO BaiTapCNTT2.VIDEO VALUES ('V211002','Kem xoi: Tap 31 - May Kool tinh yeu cua anh','312','16');
INSERT INTO BaiTapCNTT2.VIDEO VALUES ('V400002','Noi tinh yeu ket thuc - Hoang Tuan','378','0');

INSERT INTO BaiTapCNTT2.SHARE_NEW VALUES ('V100229','C905');
INSERT INTO BaiTapCNTT2.SHARE_NEW VALUES ('V211002','C120');
INSERT INTO BaiTapCNTT2.SHARE_NEW VALUES ('V400002','C357');

-- CAU 3
ALTER TABLE BaiTapCNTT2.USER_NEW
MODIFY REGDAY DATE DEFAULT SYSDATE;

-- CAU 4



-- CAU 5
SELECT * 
FROM BaiTapCNTT2.VIDEO 
WHERE AGE>=16

-- CAU 6
SELECT * 
FROM BaiTapCNTT2.CHANNEL
WHERE SUBCRIBES>=(
    SELECT MAX(SUBCRIBES)
    FROM BaiTapCNTT1.CHANNEL)

-- CAU 7
SELECT VIDEO.VIDEOID, COUNT(CHANNELID) AS AMOUNT_SHARES
FROM BaiTapCNTT2.SHARE_NEW, BaiTapCNTT2.VIDEO
WHERE SHARE_NEW.VIDEOID=VIDEO.VIDEOID AND AGE>=18
GROUP BY VIDEO.VIDEOID

-- CAU 8
SELECT *
FROM BaiTapCNTT2.VIDEO V
WHERE NOT EXISTS(
    SELECT * 
    FROM BaiTapCNTT2.CHANNEL C
    WHERE NOT EXISTS(
        SELECT * 
        FROM BaiTapCNTT2.SHARE_NEW S
        WHERE S.VIDEOID=V.VIDEOID AND S.CHANNELID=C.CHANNELID))






















