-- CAU 1
CREATE TABLE BaiTapCNTT3.HANGHANGKHONG
(
    MAHANG VARCHAR2(2) CONSTRAINT PK_HANGHANGKHONG PRIMARY KEY,
    TENHANG VARCHAR2(50),
    NGTL DATE,
    DUONGBAY NUMBER
)

CREATE TABLE BaiTapCNTT3.CHUYENBAY
(
    MACB VARCHAR2(5) CONSTRAINT PK_CHUYENBAY PRIMARY KEY,
    MAHANG VARCHAR2(2) NOT NULL,
    XUATPHAT VARCHAR2(30) NOT NULL,
    DIEMDEN VARCHAR2(30) NOT NULL,
    BATDAU DATE,
    TGBAY DECIMAL
)

CREATE TABLE BaiTapCNTT3.NHANVIEN
(
    MANV VARCHAR2(4) CONSTRAINT PK_NHANVIEN PRIMARY KEY,
    HOTEN VARCHAR(50),
    GIOITINH VARCHAR2(3),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR2(30)
)

CREATE TABLE BaiTapCNTT3.PHANCONG
(
    MACB VARCHAR2(5),
    MANV VARCHAR2(4),
    NHIEMVU VARCHAR2(30)
)

ALTER TABLE BaiTapCNTT3.CHUYENBAY 
ADD CONSTRAINT FK_CHUYENBAY FOREIGN KEY (MAHANG) REFERENCES BaiTapCNTT3.HANGHANGKHONG(MAHANG)

ALTER TABLE BaiTapCNTT3.PHANCONG
ADD CONSTRAINT FK_PC1 FOREIGN KEY (MACB) REFERENCES BaiTapCNTT3.CHUYENBAY(MACB)

ALTER TABLE BaiTapCNTT3.PHANCONG
ADD CONSTRAINT FK_PC2 FOREIGN KEY (MANV) REFERENCES BaiTapCNTT3.NHANVIEN(MANV)

-- CAU 2
ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

INSERT INTO BaiTapCNTT3.HANGHANGKHONG VALUES ('VN','Vietnam Airlines','15/01/1956',52);
INSERT INTO BaiTapCNTT3.HANGHANGKHONG VALUES ('VJ','Vietjet Air','25/12/2011',33);
INSERT INTO BaiTapCNTT3.HANGHANGKHONG VALUES ('BL','Jetstar Pacific Airlines','01/12/1990',13);

INSERT INTO BaiTapCNTT3.CHUYENBAY VALUES ('VN550','VN','TPHCM','Singapore',' 20/12/2015 13:15:00 ',2);
INSERT INTO BaiTapCNTT3.CHUYENBAY VALUES ('VJ331','VJ','Da Nang','Vinh',' 28/12/2015 22:30:00 ',1);
INSERT INTO BaiTapCNTT3.CHUYENBAY VALUES ('BL696','BL','TPHCM','Da Lat',' 24/12/2015 06:00:00 ',0.5);

INSERT INTO BaiTapCNTT3.NHANVIEN VALUES ('NV01','Lam Van Ben','Nam','10/09/1978','05/05/2000','Phi cong');
INSERT INTO BaiTapCNTT3.NHANVIEN VALUES ('NV02','Duong Thi Luc','Nu','22/03/1989','12/11/2013','Tiep vien');
INSERT INTO BaiTapCNTT3.NHANVIEN VALUES ('NV03','Hoang Thanh Tung','Nam','29/07/1983','11/04/2007','Tiep vien');

INSERT INTO BaiTapCNTT3.PHANCONG VALUES ('VN550','NV01','Co truong');
INSERT INTO BaiTapCNTT3.PHANCONG VALUES ('VN550','NV02','Tiep vien');
INSERT INTO BaiTapCNTT3.PHANCONG VALUES ('BL696','NV03','Tiep vien truong');

-- CAU 3
ALTER TABLE BaiTapCNTT3.NHANVIEN
ADD CONSTRAINT CK_NV CHECK (CHUYENMON IN ('Phi cong', 'Tiep vien'))

-- CAU 4


-- CAU 5
SELECT * 
FROM BaiTapCNTT3.NHANVIEN
WHERE EXTRACT(MONTH FROM(NGSINH))=7

-- CAU 6
SELECT CHUYENBAY.MACB
FROM BaiTapCNTT3.CHUYENBAY, BaiTapCNTT3.PHANCONG
WHERE CHUYENBAY.MACB=PHANCONG.MACB
GROUP BY CHUYENBAY.MACB
HAVING COUNT(MANV)>=(
    SELECT MAX(COUNT(MANV))
    FROM BaiTapCNTT3.PHANCONG
    GROUP BY MACB)

-- CAU 7
SELECT MAHANG, XUATPHAT, COUNT(MANV) AS AMOUNT_NV
FROM BaiTapCNTT3.CHUYENBAY LEFT JOIN BaiTapCNTT3.PHANCONG ON CHUYENBAY.MACB=PHANCONG.MACB 
WHERE XUATPHAT='Da Nang'
GROUP BY CHUYENBAY.MACB, MAHANG, XUATPHAT
HAVING COUNT(MANV)<2

-- CAU 8
SELECT *
FROM BaiTapCNTT3.NHANVIEN NV
WHERE NOT EXISTS(
    SELECT * 
    FROM BaiTapCNTT3.CHUYENBAY CB
    WHERE NOT EXISTS(
        SELECT * 
        FROM BaiTapCNTT3.PHANCONG PC
        WHERE PC.MACB=CB.MACB AND PC.MANV=NV.MANV))











